name: Manual Lua Check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Lua check
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color --codes -q"
          annotate: warning
